// <auto-generated />
using System;
using Hybrid_Crypt_IRC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hybrid_Crypt_IRC.Migrations.ChatCrypt
{
    [DbContext(typeof(ChatCryptContext))]
    partial class ChatCryptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Hybrid_Crypt_IRC.Models.ChatGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GroupName");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.HasKey("Id");

                    b.ToTable("GroupChat");
                });

            modelBuilder.Entity("Hybrid_Crypt_IRC.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ChatGroupId");

                    b.Property<string>("MessageText");

                    b.Property<string>("SenderId");

                    b.HasKey("Id");

                    b.HasIndex("ChatGroupId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Hybrid_Crypt_IRC.Models.PublicKeys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ChatGroupId");

                    b.Property<string>("PublicKey");

                    b.HasKey("Id");

                    b.HasIndex("ChatGroupId");

                    b.ToTable("PublicKeys");
                });

            modelBuilder.Entity("Hybrid_Crypt_IRC.Models.Message", b =>
                {
                    b.HasOne("Hybrid_Crypt_IRC.Models.ChatGroup", "ChatGroup")
                        .WithMany("Messages")
                        .HasForeignKey("ChatGroupId");
                });

            modelBuilder.Entity("Hybrid_Crypt_IRC.Models.PublicKeys", b =>
                {
                    b.HasOne("Hybrid_Crypt_IRC.Models.ChatGroup")
                        .WithMany("PublicKeys")
                        .HasForeignKey("ChatGroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
